### ISSUE TITLE
[Request]  Please Add Adreno Boost Parameter

### ISSUE THREAD

**Issue by imzf** [morogoku/MTweaks-KernelAdiutorMOD#2]

**Comment by morogoku** [comment]
I need the path of files in sysfs

**Comment by imzf** [comment]
@morogoku 
echo 1 > /sys/class/kgsl/kgsl-3d0/devfreq/adrenoboost

* 0 for off , 1 for low , 2 for medium , 3 for high *

**Comment by morogoku** [comment]
It's done.

https://github.com/morogoku/MTweaks-KernelAdiutorMOD/commit/0400fbaf03d5af50454ad2af223eeae0ff8c475f


included in MTweaks 2.8.5

**Comment by imzf** [comment]
@morogoku  thank you。
