### ISSUE TITLE
[REQUEST] Add Adreno Idler & Simple GPU algorithm

### ISSUE THREAD

**Issue by Pg-Pi3Gey** [morogoku/MTweaks-KernelAdiutorMOD#3]
https://github.com/Grarak/KernelAdiutor/commit/7ba68dedc48c92bda3901f1308dd3a048070abae

https://github.com/Grarak/KernelAdiutor/commit/ea9375371ba84d9cb42837aa2f0b44bf5f6d7c7c

**Comment by morogoku** [comment]
I've added adreno settings, do you want to try it?
Have you got telegram? You can contact with me: @Morogoku
