### ISSUE TITLE
Doesn't recognise the spectrum support

### ISSUE THREAD

**Issue by ktommy91** [morogoku/MTweaks-KernelAdiutorMOD#6]
Since I moved the scripts to /vendor(to get working with enforcing pie ROMs) the app doesnt recognise the spectrum support.

**Comment by morogoku** [comment]
do you mean the init.spectrum.sh? where have you moved it exactly? to /vendor/init.spectrum.sh?.

Edit:
I'm going to change the support check, so that it works

**Comment by ktommy91** [comment]
> do you mean the init.spectrum.sh? where have you moved it exactly? to /vendor/init.spectrum.sh?.
> 
> Edit:
> I'm going to change the support check, so that it works

To /vendor/etc/init/hw but the init.spectrum.sh will move again to /vendor/bin

**Comment by morogoku** [comment]
I think it's resolved
[https://github.com/morogoku/MTweaks-KernelAdiutorMOD/commit/8e1ce7aa46a3ab07c74790408a50377af8f49c92](url)

Now It checks the prop spectrum.support


tomorrow will come new update
