### ISSUE TITLE
Apply spectrum on boot

### ISSUE THREAD

**Issue by Boulder08** [morogoku/MTweaks-KernelAdiutorMOD#8]
Apparently the selectes spectrum cannot be applied on boot, at the that's what the ThunderTweaks mod author told me. Would it be possible to implement this? Or other easy way to make the spectrum-included settings applied. Now I need to change the spectrum, activate apply on boot for each section and change each item once back and forth so they will then be set during boot.

**Comment by morogoku** [comment]
Is a problem of Android Pie with ramdisk implementation of the init.spectrum files,
Is not a problem of Mtweaks.
Is a kernel problem

But I will solved in my next kernel v7.2
